#!/bin/bash

# A script to install or update the latest stable version of Go on Ubuntu.
# generated by Gemini

# --- Script Start ---

# Check for sudo privileges
if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run with sudo privileges."
    exit 1
fi

# Function to check for a successful command execution
check_success() {
    if [ $? -ne 0 ]; then
        echo "Error: $1 failed. Exiting."
        exit 1
    fi
}

# 1. Remove any previous Go installations
echo "--- Removing any existing Go installations ---"
rm -rf /usr/local/go
check_success "Removal of old Go directory"

# 2. Get the latest Go version from the official downloads page
echo "--- Fetching the latest Go version ---"
GO_LATEST_VERSION=$(curl -s https://go.dev/VERSION?m=text | head -n 1)
check_success "Fetching Go version"
echo "Found latest version: $GO_LATEST_VERSION"

# 3. Construct the download URL
GO_DOWNLOAD_URL="https://go.dev/dl/${GO_LATEST_VERSION}.linux-amd64.tar.gz"
echo "Download URL: $GO_DOWNLOAD_URL"

# 4. Download the tarball
echo "--- Downloading the Go tarball ---"
wget -q --show-progress "$GO_DOWNLOAD_URL" -O /tmp/go_temp.tar.gz
check_success "Downloading Go tarball"

# 5. Extract the tarball to /usr/local
echo "--- Extracting the tarball to /usr/local ---"
tar -C /usr/local -xzf /tmp/go_temp.tar.gz
check_success "Extracting Go tarball"

# 6. Set Go environment variables for all users
echo "--- Setting up Go environment variables ---"
GO_PROFILE_FILE="/etc/profile.d/go_env.sh"
if [ ! -f "$GO_PROFILE_FILE" ]; then
    echo "# Go Environment Variables" > "$GO_PROFILE_FILE"
    echo "export PATH=\$PATH:/usr/local/go/bin" >> "$GO_PROFILE_FILE"
    echo "export GOROOT=/usr/local/go" >> "$GO_PROFILE_FILE"
    echo "export GOPATH=\$HOME/go" >> "$GO_PROFILE_FILE"
    echo "Successfully created and populated $GO_PROFILE_FILE"
else
    # Check if the file contains the Go environment variables, if not, add them
    if ! grep -q "export PATH=\$PATH:/usr/local/go/bin" "$GO_PROFILE_FILE"; then
        echo "export PATH=\$PATH:/usr/local/go/bin" >> "$GO_PROFILE_FILE"
        echo "export GOROOT=/usr/local/go" >> "$GO_PROFILE_FILE"
        echo "export GOPATH=\$HOME/go" >> "$GO_PROFILE_FILE"
        echo "Updated $GO_PROFILE_FILE with Go environment variables."
    else
        echo "Go environment variables already exist in $GO_PROFILE_FILE. No changes made."
    fi
fi
check_success "Setting environment variables"

# 7. Clean up the temporary file
echo "--- Cleaning up temporary files ---"
rm /tmp/go_temp.tar.gz
check_success "Cleaning up temporary file"

# 8. Verify the installation
echo "--- Verification ---"
echo "Please restart your shell or run 'source /etc/profile.d/go_env.sh' to apply changes."
echo "Then, run 'go version' to confirm the installation."
echo "Script finished successfully!"

# --- Script End ---
